services:
  # Use root/example as user/password credentials
  mongo:
    image: mongo:6.0
    container_name: oneclass-mongo-1
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - mongodata:/data/db
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
  
  # for only executing mongo scripts
  mongosetup:
    image: mongo:6.0
    environment:
      - HOSTNAME=${HOSTNAME}
    depends_on:
      - mongo
    volumes:
      - .:/scripts
    restart: "no"

    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]

  sql:
    image: mysql:8.0
    container_name: oneclass-sql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - sqldata:/data/db/var/lib/mysql
    ulimits:
      nofile:
        soft: 20000
        hard: 40000

  postgre:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - sqldata:/data/db/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: example

  
  # https://redis.io/learn/operate/redis-at-scale/talking-to-redis/configuring-a-redis-server
  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080

volumes:
  mongodata:
  sqldata:
  postgredata:
