version: "3.1"

services:
  # Use root/example as user/password credentials
  mongo:
    image: mongo:6.0
    container_name: oneclass-mongo-1
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - mongodata:/data/db
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
  
  # for only executing mongo scripts
  mongosetup:
    image: mongo:6.0
    network_mode: host
    depends_on:
      - mongo
    volumes:
      - .:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]

  sql:
    image: mysql:8
    container_name: oneclass-sql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - sqldata:/data/db/var/lib/mysql
    ulimits:
      nofile:
        soft: 20000
        hard: 40000

  postgre:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - sqldata:/data/db/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: example
  
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080
    
volumes:
  mongodata:
  sqldata:
  postgredata:
